### ISSUE TITLE
Can you add details about the pins you are using in your README

### ISSUE THREAD

**Issue by rw86347** [MetalPhreak/ESP8266_SPI_Driver#1]
I am using the Olimex ESP8266 and am wanting to use your device driver can you speak in greater detail abou which pins you are using, and how you prevent colliding with the flash file access?

**Comment by MetalPhreak** [comment]
Added a table showing the HSPI pins.

The main SPI module is in use by the flash rom chip. I don't think you can use it easily while it's used for ROM. There is also a mode to mux the HSPI pins onto the normal SPI pins, but again, I haven't tested it. 

For the Olimex board, just match the GPIO pin numbers with the HSPI functions. Pin name is the name given on the espressif ESP8266 chip datasheet.
