### ISSUE TITLE
spi_clock with pre/postdivider set to 0

### ISSUE THREAD

**Issue by bkolb** [MetalPhreak/ESP8266_SPI_Driver#3]
In spi_clock  I can see the following line (107)

```
    if((prediv==0)|(cntdiv==0)){
```

To my understanding that should be changed to a logical OR, correct?

**Comment by MetalPhreak** [comment]
Doesn't matter either way. 

(prediv==0) evaluates to 0 or 1
(cntdiv==0) evaluates to 0 or 1

If either is 1, then | or || still gives a true result. 

(|| may be better from a readability perspective though)
