### ISSUE TITLE
GPIO15 use for boot?

### ISSUE THREAD

**Issue by tinamore** [MetalPhreak/ESP8266_SPI_Driver#4]
Hi
ESP8266_SPI_Driver is a great project
I use your driver for communication between Arduino vs Esp8266
But i don't understand why you choice pin GPIO15    for CS / SS, because GPIO15 need keep to LOW for boot Normal: https://github.com/esp8266/esp8266-wiki/wiki/Boot-Process
How to Float GPIO15 out of LOW after boot for Use it for CS / SS ?

**Comment by someburner** [comment]
10K pulldown to ground works fine for me.

**Comment by MetalPhreak** [comment]
There is no "choice". The CS/SS on GPIO15 is hardware controlled by the HSPI module.

As someburner says, a pulldown works fine for boot (it's what I use).
