### ISSUE TITLE
Slave Mode?

### ISSUE THREAD

**Issue by paulmand3l** [MetalPhreak/ESP8266_SPI_Driver#5]
I'm having a heck of a time trying to figure out the documentation for SPI Slave mode on the ESP8266. All I have to go on is this post http://bbs.espressif.com/viewtopic.php?t=77

As somebody with experience diving into SPI registers, any way you can point me in the right direction, or any plans to add slave mode support to this driver library?

Thanks!

**Comment by MetalPhreak** [comment]
Sorry, I haven't looked into SPI slave mode at all. All of the registers for it are different to the normal SPI control registers. Best to look at the Espressif SDK spi code and reverse engineer it from there (there's some slave spi functions in there along with the normal spi master commands).
