### ISSUE TITLE
Possible Doc error in README.md

### ISSUE THREAD

**Issue by nkolban** [MetalPhreak/ESP8266_SPI_Driver#6]
In the `README.md` the pins are documented:
- MTDI - GPIO12
- MTCK - GPIO13
- MTMS - GPIO14
- MTDO - GPIO15

I think this may be an error and might be:
- MTDI - GPIO12
- MTDO - GPIO13
- MTCK - GPIO14
- MTMS - GPIO15

**Comment by MetalPhreak** [comment]
MTDI/MTCK/MTMS/MTDO "PIN NAME" is from the datasheet (the actual pad on the chip). They don't reference the SPI module pins which are in the HSPI Function column. 

ie MTDI (pin 10 on chip) is HSPI MISO / GPIO12
